# Generated by Django 3.1.6 on 2021-02-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='title',
        ),
    ]
