# Generated by Django 3.1.6 on 2021-02-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20210217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Имя города'),
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='street',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Имя улицы'),
        ),
    ]
