# Generated by Django 3.1.6 on 2021-02-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20210219_1241'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='house',
            field=models.CharField(max_length=128, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя города'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.street', verbose_name='Улица'),
        ),
    ]
